#!/usr/bin/env python3
"""Generate browsable age pages into a Logseq graph from person/event data.

Writes three auto-generated pages (overwritten on each run):
  * Ages.md          — master table of everyone's dates + ages, and who still needs dates
  * Life Parallels.md — for each elder, the year they were the reference person's current age
  * Timeline.md      — events in order, each annotated with the family's ages at that moment

Usage:
  python age_pages.py [graph] [--apply]
      graph   configured graph name (default: daddipedia)
      --apply actually write the pages (otherwise prints them to stdout)
"""
import sys
from datetime import date

sys.path.insert(0, "/data/BUSINESS/Burnilab/markdown-graph-mcp")
import logseq_graphs as lg
import age

FAMILY_RELS = {"self", "mother", "father", "parent", "child", "son", "daughter",
               "sister", "brother", "sibling", "partner", "spouse", "wife", "husband"}
GEN_NOTE = "> Auto-generated by `age_pages.py` — edits here are overwritten on regeneration."


def today_stamp():
    d = date.today()
    return f"[[{d.year:04d}/{d.month:02d}/{d.day:02d}]]"


def is_family(p):
    return lg._normalize_prop(p.relationship) in FAMILY_RELS


def link(p):
    return f"[[{p.title}]]"


def born_str(p):
    if not p.born:
        return ""
    return p.born.raw


def table_block(headers, rows):
    """One Logseq block holding a markdown table (continuation lines indented)."""
    out = ["- | " + " | ".join(headers) + " |"]
    out.append("  | " + " | ".join("---" for _ in headers) + " |")
    for r in rows:
        out.append("  | " + " | ".join(r) + " |")
    return "\n".join(out)


def signed_years(ref, on):
    if not (ref.born and ref.born.has_year):
        return None
    return age.years_between(ref.born.to_date(), on)


# ---------------------------------------------------------------------------

def gen_ages(people, ref, today):
    rows = []
    needs = []
    dated = [p for p in people if p.born and p.born.has_year]
    dated.sort(key=lambda p: p.born.to_date())
    for p in dated:
        r = age.age_on(p, today)
        if r.status == "deceased":
            age_col = f"† {r.age} (at death)"
        elif r.status == "alive":
            age_col = str(r.age)
        elif r.status == "unborn":
            age_col = "not yet born"
        else:
            age_col = "?"
        died_col = p.died.raw if p.died else ""
        # Reference's age when this person was born / died.
        b = signed_years(ref, p.born.to_date())
        born_ref = str(b) if (b is not None and b >= 0) else ""
        died_ref = ""
        if p.died and p.died.has_year:
            d = signed_years(ref, p.died.to_date(default_month=12, default_day=31))
            died_ref = str(d) if (d is not None and d >= 0) else ""
        rows.append([link(p), born_str(p), died_col, age_col, born_ref, died_ref])
    for p in people:
        if not (p.born and p.born.has_year):
            needs.append(link(p))

    ref_age = age.age_on(ref, today).age
    lines = [
        "type:: #Report",
        "icon:: 🎂",
        f"generated:: {today_stamp()}",
        "",
        f"- {GEN_NOTE}",
        f"- Reference: {link(ref)} — born {born_str(ref)}, currently {ref_age}.",
        "- ## Ages",
        table_block(
            ["Person", "Born", "Died", "Age", f"{ref.title}'s age at their birth",
             f"{ref.title}'s age at their death"],
            rows),
    ]
    if needs:
        lines.append(f"- ## Dates needed ({len(needs)})")
        lines.append("  - " + ", ".join(needs))
    return "\n".join(lines) + "\n"


def gen_parallels(people, events, ref, today):
    ref_age = age.age_on(ref, today).age
    fam_titles = {p.title for p in people if is_family(p)}
    elders = [p for p in people
              if p is not ref and is_family(p) and p.born and p.born.has_year
              and p.born.year < ref.born.year]
    elders.sort(key=lambda p: p.born.to_date())
    dated_events = [e for e in events if e.date and e.date.has_year]

    lines = [
        "type:: #Report",
        "icon:: 🪞",
        f"generated:: {today_stamp()}",
        "",
        f"- {GEN_NOTE}",
        f"- {link(ref)} is currently **{ref_age}**. Below: the year each elder was that same age, and what surrounded it.",
    ]
    for p in elders:
        year = p.born.year + ref_age
        on = p.born.to_date().replace(year=year)
        others = [f"{link(r.person)} {r.age}" for r in
                  sorted((age.age_on(q, on) for q in people), key=lambda r: -(r.age or 0))
                  if r.status == "alive" and r.person is not p and r.person.title in fam_titles]
        near = [e for e in dated_events if abs(e.date.year - year) <= 1]
        lines.append(f"- ### {link(p)} was {ref_age} in {year}")
        lines.append(f"  - Born {born_str(p)} → turned {ref_age} on [[{year:04d}/{on.month:02d}/{on.day:02d}]].")
        if others:
            lines.append("  - Family then: " + "; ".join(others))
        if near:
            near.sort(key=lambda e: e.date.year)
            lines.append("  - Around then: " + "; ".join(f"{e.date.year} [[{e.title}]]" for e in near))
    return "\n".join(lines) + "\n"


def gen_timeline(people, events, ref):
    fam = [p for p in people if is_family(p)]
    fam_titles = {p.title for p in fam}
    dated = [e for e in events if e.date and e.date.has_year]
    dated.sort(key=lambda e: (e.date.year, e.date.month or 0, e.date.day or 0))
    undated = [e for e in events if not (e.date and e.date.has_year)]

    lines = [
        "type:: #Report",
        "icon:: 📜",
        f"generated:: {today_stamp()}",
        "",
        f"- {GEN_NOTE}",
        f"- Life events with the immediate family's ages at each moment. Reference {link(ref)}. ⭐ = critical.",
        "- ## Timeline",
    ]
    for e in dated:
        snap = age.annotate_event(e, people, reference=ref)
        ages = []
        for r in snap.results:
            if r.person.title not in fam_titles:
                continue
            if r.status == "alive":
                ages.append(f"{link(r.person)} {r.age}")
            elif r.status == "deceased":
                ages.append(f"{link(r.person)} †")
        star = " ⭐" if e.critical else ""
        cat = f" _{e.category}_" if e.category else ""
        agestr = (" — " + "; ".join(ages)) if ages else ""
        lines.append(f"  - {e.date.year} [[{e.title}]]{cat}{star}{agestr}")
    if undated:
        lines.append("- ## Undated")
        for e in undated:
            lines.append(f"  - [[{e.title}]] _{e.category}_")
    return "\n".join(lines) + "\n"


def main():
    args = [a for a in sys.argv[1:] if a != "--apply"]
    graph = args[0] if args else "daddipedia"
    apply = "--apply" in sys.argv
    graph_name, graph_root = lg.resolve_graph(graph)
    today = date.today()

    people = age.load_people(graph_root)
    events = age.load_events(graph_root)
    ref = age.find_reference(people, None)
    if ref is None:
        sys.exit("No relationship:: self page found.")

    pages = {
        "Ages": gen_ages(people, ref, today),
        "Life Parallels": gen_parallels(people, events, ref, today),
        "Timeline": gen_timeline(people, events, ref),
    }
    for title, content in pages.items():
        path = lg.page_path(graph_root, title)
        if apply:
            if path.exists():
                lg.backup_page_file(path, graph_root)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path}")
        else:
            print(f"===== {title}.md =====")
            print(content)


if __name__ == "__main__":
    main()
